    .byte #$00
    .byte #$86
    .byte #$86
    .byte #$86
    .byte #$86
    .byte #$6A
    .byte #$6A
    .byte #$68
    .byte #$68
    .byte #$4F
    .byte #$4F
    .byte #$A8
    .byte #$A8
    .byte #$45
    .byte #$45
    .byte #$BF
    .byte #$BF
